### ISSUE TITLE
Facing issue while installing using pip

### ISSUE THREAD

**Issue by himanshu034** [fiddler-labs/fiddler-auditor#31]
I am trying to install fiddler-auditor on my windows system having python version 3.8.10. I tried below command to install the fiddler-auditor.
pip install fiddler-auditor==0.0.2

I am getting below issue.
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\decdpdev\AppData\Local\Temp\2\pip-install-8ehkyvdt\checklist_e78d9343558d4dfdbdc643849914e703\setup.py", line 56, in <module>
        setup(name='checklist',
      File "c:\himanshu\virtual_env\fiddler_auditor_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\decdpdev\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\decdpdev\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\decdpdev\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\decdpdev\AppData\Local\Temp\2\pip-install-8ehkyvdt\checklist_e78d9343558d4dfdbdc643849914e703\setup.py", line 53, in run
        enable_visual_interface()
      File "C:\Users\decdpdev\AppData\Local\Temp\2\pip-install-8ehkyvdt\checklist_e78d9343558d4dfdbdc643849914e703\setup.py", line 14, in enable_visual_interface
        notebook.nbextensions.install_nbextension_python(
    AttributeError: module 'notebook' has no attribute 'nbextensions'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/38/b3/8511f50025b9fc66f5feacf9eb2db044c321f4026b6937cb3820f29e9c1d/checklist-0.0.11.tar.gz#sha256=427cf87dbf47ce9f9ab059a9bbf393d9ebf967e266f8fca377420bd6995a95ac (from https://pypi.org/simple/checklist/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement checklist==0.0.11 (from fiddler-auditor) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
ERROR: No matching distribution found for checklist==0.0.11

Seems there is dependency of package: checklist which is not getting installed because of AttributeError: module 'notebook' has no attribute 'nbextensions'.

Please help me to resolve or let me know if I am doing anything wrong.

**Comment by iterix** [comment]
@himanshu034 Thanks for sharing the trace! That's very helpful. We don't test explicitly on windows yet but I will look into it. For now, can I suggest windows and mac-os if that's a possibility.
